/* Generated by ./import-bg.sh — do not edit by hand.
   Maps each time-of-day band to the images the dashboard rotates through.
   Bands with no imported photos fall back to the generated vector scenes. */
window.MIQAAT_BACKGROUNDS = {
  sets: {
    dawn: ["dawn1", "dawn2", "dawn3"],
    day: ["day1", "day2", "day3"],
    dusk: ["dusk1", "dusk2", "dusk3"],
    night: ["night1", "night2", "night3"]
  }
};
