#!/usr/bin/env bash
# Import your own background photos.
#
#   mkdir -p incoming/dusk && cp ~/Downloads/mosque-sunset.jpg incoming/dusk/
#   ./import-bg.sh
#
# Drop images into incoming/<band>/ where <band> is one of dawn, day, dusk,
# night — the dashboard picks the band from the sun and then chooses randomly
# among that band's images, re-rolling every few minutes.
#
# Each image is cropped to fill 1920x1080 (centred), re-encoded as JPEG, and
# registered in js/bgmanifest.js. Nothing in the app hardcodes filenames, so
# adding images needs no code change.
#
# Composition note: the dashboard puts the wordmark top-left, the clock
# top-right, and an opaque prayer strip across y=648..790. Pick images whose
# detail lives in the middle band and whose corners are calm.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"
SRC="incoming"
OUT="assets/bg"
MANIFEST="js/bgmanifest.js"
BANDS=(dawn day dusk night)

command -v ffmpeg >/dev/null || { echo "ffmpeg required: brew install ffmpeg" >&2; exit 1; }
mkdir -p "$OUT"

if [ ! -d "$SRC" ]; then
  echo "No $SRC/ directory. Create it and add images:"
  for b in "${BANDS[@]}"; do echo "  mkdir -p $SRC/$b"; done
  exit 1
fi

# Keep the generated vector art as a fallback; only user imports are numbered
# with the "photo" prefix so the two never collide.
rm -f "$OUT"/photo-*.jpg

declare -a manifest_lines
total=0

for band in "${BANDS[@]}"; do
  [ -d "$SRC/$band" ] || continue
  n=0
  names=()
  while IFS= read -r -d '' f; do
    n=$((n + 1))
    name="photo-$band$n"
    # scale to cover, then centre-crop to exactly 1920x1080
    ffmpeg -nostdin -v error -y -i "$f" \
      -vf "scale=1920:1080:force_original_aspect_ratio=increase,crop=1920:1080" \
      -q:v 4 "$OUT/$name.jpg"
    names+=("\"$name\"")
    total=$((total + 1))
    printf "  %-16s <- %s  (%s)\n" "$name.jpg" "$(basename "$f")" "$(du -h "$OUT/$name.jpg" | cut -f1)"
  done < <(find "$SRC/$band" -maxdepth 1 -type f \
             \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \) -print0 | sort -z)

  if [ "$n" -gt 0 ]; then
    manifest_lines+=("    $band: [$(IFS=,; echo "${names[*]}")]")
  else
    # no photos for this band: fall back to the three generated scenes
    manifest_lines+=("    $band: [\"${band}1\", \"${band}2\", \"${band}3\"]")
  fi
done

{
  echo "/* Generated by ./import-bg.sh — do not edit by hand."
  echo "   Maps each time-of-day band to the images the dashboard rotates through."
  echo "   Bands with no imported photos fall back to the generated vector scenes. */"
  echo "window.MIQAAT_BACKGROUNDS = {"
  echo "  sets: {"
  printf '%s\n' "$(IFS=$'\n'; echo "${manifest_lines[*]}" | sed '$ !s/$/,/')"
  echo "  }"
  echo "};"
} > "$MANIFEST"

echo "imported $total image(s); wrote $MANIFEST"
echo "total assets/bg: $(du -sh "$OUT" | cut -f1)"
